name: nostr_pay_kids
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+9

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  connectivity_plus: ^6.1.4
  # device_info_plus: ^11.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_fgbg: ^0.7.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  logging: ^1.3.0
  # ndk: ^0.5.1
  ndk:
    git:
      url: https://github.com/relaystr/ndk
      path: packages/ndk
      ref: nwc-connect-timeout
  path: ^1.9.1
  path_provider: ^2.1.5
  posthog_flutter: ^4.0.0
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  mobile_scanner: <7.0.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  bolt11_decoder:
    git: https://github.com/fusion44/dart_bolt11_decoder
  timeago: ^3.7.1
  another_flushbar: ^1.12.30
  flutter_confetti: ^0.5.1
  typethis: ^1.0.3
  auto_size_text: ^3.0.0
  flutter_app_group_directory: ^1.1.0
  shared_preference_app_group: ^1.1.1
  dio: ^5.8.0+1
  flutter_animate: ^4.5.2
  share_plus: ^11.0.0
  package_info_plus: ^8.3.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/mascot/

  fonts:
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/ComicNeue-Italic.ttf
          style: italic
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ComicNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/ComicNeue-LightItalic.ttf
          weight: 300
          style: italic

flutter_native_splash:
  color: "#FFE274"
  image: "assets/mascot/UFO_Splash.png"
  # We are only configuring for iOS right now
  ios: true
  android: false # You can set this to true later if you support Android
